### PR TITLE
minor fixes for LOVE2D 11.x

### PR DESCRIPTION
**Pull request by gingerbeardman**
I've never really used LOVE2D before, and I only looked at your code briefly, so I don't know why these changes are needed.

But, without these fixes some parts look broken:

*Part 4* (alternating colours blown out to white)
Screen shot 2021-09-27 at 13 27 05

*Part 5* (Gouraud shading blown out to white/black)
Screen shot 2021-09-27 at 13 30 00

### CODE REVIEW

**Comment by jonasgeiler** [comment]
Oh I remember the good old 0-1 vs. 0-255 color problem of LOVE2D.... I think they changed the scaling from one version to another and everyone got confused lmao

Anyways, is this ready to merge?

**Comment by gingerbeardman** [comment]
Yes, merge it.

Do you want me to submit the flat shaded Part5 separately? I think it's useful for people.

I won't submit any optimisations because I think they make the code less readable.

**Comment by jonasgeiler** [comment]
> Do you want me to submit the flat shaded Part5 separately? I think it's useful for people.

No, it's alright I think... Or do you mean it's useful if they ARE seperated? Just do whatever is more useful 😅


> I won't submit any optimisations because I think they make the code less readable.

I didn't know the code was readable before haha  
But yeah that's fine!

Thanks again!

**Comment by gingerbeardman** [comment]
I'll file another PR soon for Part5-flat

**Pull request merged**
